language: c

env:
    - SMVERSION=1.10

matrix:
    fast_finish: true

before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib
    - sudo apt-get install lynx
    - sudo apt-get install lib32stdc++6

before_script:
    - SMLATEST=`curl "https://www.sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux"`
    - SMPACKAGE="https://www.sourcemod.net/smdrop/$SMVERSION/$SMLATEST"
    - wget $SMPACKAGE
    - tar -xzf $(basename "$SMPACKAGE")
    - cp Modular_LS.sp addons/sourcemod/scripting/
    - cp include/morecolors.inc addons/sourcemod/scripting/include
    - cp include/EventLogs.inc addons/sourcemod/scripting/include
    - cp include/steamtools.inc addons/sourcemod/scripting/include
    - cp include/SteamWorks.inc addons/sourcemod/scripting/include
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - chmod +x compile.sh

script:
    - ./compile.sh Modular_LS.sp

deploy:
  provider: releases
  api_key: "$githubkey"
  file: "$TRAVIS_BUILD_DIR/addons/sourcemod/scripting/compiled/Modular_LS.smx"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false
